# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:44
from __future__ import unicode_literals
from __future__ import absolute_import

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_art', models.CharField(max_length=50)),
                ('talla', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=10)),
                ('fecha_llegada', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
