# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retiro', '0002_auto_20171007_1927'),
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='retiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retiro.retiro'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='accesorio',
            field=models.ManyToManyField(to='articulo.accesorio'),
        ),
    ]
